"""initialize schema

Revision ID: 254c73c7a415
Revises:
Create Date: 2026-04-27 03:03:20.753874

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "254c73c7a415"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "benchmarks",
        "labels",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        type_=sa.ARRAY(sa.String()),
        existing_nullable=True,
    )
    op.alter_column(
        "benchmarks",
        "benchmark_refs",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        type_=sa.ARRAY(sa.String()),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_benchmarks_title"), table_name="benchmarks")
    op.create_index(op.f("ix_benchmarks_title"), "benchmarks", ["title"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_benchmarks_title"), table_name="benchmarks")
    op.create_index(op.f("ix_benchmarks_title"), "benchmarks", ["title"], unique=False)
    op.alter_column(
        "benchmarks",
        "benchmark_refs",
        existing_type=sa.ARRAY(sa.String()),
        type_=postgresql.ARRAY(sa.TEXT()),
        existing_nullable=True,
    )
    op.alter_column(
        "benchmarks",
        "labels",
        existing_type=sa.ARRAY(sa.String()),
        type_=postgresql.ARRAY(sa.TEXT()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
