"""init schema

Revision ID: 2b7dacbd507b
Revises: 
Create Date: 2026-04-28 03:34:10.117416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b7dacbd507b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('auto_scan', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_hostname'), 'assets', ['hostname'], unique=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_ip_address'), 'assets', ['ip_address'], unique=False)
    op.create_table('benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('profile', sa.String(length=255), nullable=True),
    sa.Column('labels', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('benchmark_refs', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmarks_id'), 'benchmarks', ['id'], unique=False)
    op.create_index(op.f('ix_benchmarks_title'), 'benchmarks', ['title'], unique=True)
    op.create_table('audit_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('benchmark_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_infos_asset_id'), 'audit_infos', ['asset_id'], unique=False)
    op.create_index(op.f('ix_audit_infos_benchmark_id'), 'audit_infos', ['benchmark_id'], unique=False)
    op.create_index(op.f('ix_audit_infos_id'), 'audit_infos', ['id'], unique=False)
    op.create_index(op.f('ix_audit_infos_task_id'), 'audit_infos', ['task_id'], unique=True)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benchmark_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('index', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('reg_key', sa.Text(), nullable=True),
    sa.Column('reg_item', sa.Text(), nullable=True),
    sa.Column('reg_option', sa.Text(), nullable=True),
    sa.Column('audit_policy_subcategory', sa.Text(), nullable=True),
    sa.Column('right_type', sa.Text(), nullable=True),
    sa.Column('value_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_benchmark_id'), 'rules', ['benchmark_id'], unique=False)
    op.create_index(op.f('ix_rules_id'), 'rules', ['id'], unique=False)
    op.create_index(op.f('ix_rules_type'), 'rules', ['type'], unique=False)
    op.create_table('audit_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_info_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('actual_value', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['audit_info_id'], ['audit_infos.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_items_audit_info_id'), 'audit_items', ['audit_info_id'], unique=False)
    op.create_index(op.f('ix_audit_items_id'), 'audit_items', ['id'], unique=False)
    op.create_index(op.f('ix_audit_items_rule_id'), 'audit_items', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_items_rule_id'), table_name='audit_items')
    op.drop_index(op.f('ix_audit_items_id'), table_name='audit_items')
    op.drop_index(op.f('ix_audit_items_audit_info_id'), table_name='audit_items')
    op.drop_table('audit_items')
    op.drop_index(op.f('ix_rules_type'), table_name='rules')
    op.drop_index(op.f('ix_rules_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_benchmark_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_audit_infos_task_id'), table_name='audit_infos')
    op.drop_index(op.f('ix_audit_infos_id'), table_name='audit_infos')
    op.drop_index(op.f('ix_audit_infos_benchmark_id'), table_name='audit_infos')
    op.drop_index(op.f('ix_audit_infos_asset_id'), table_name='audit_infos')
    op.drop_table('audit_infos')
    op.drop_index(op.f('ix_benchmarks_title'), table_name='benchmarks')
    op.drop_index(op.f('ix_benchmarks_id'), table_name='benchmarks')
    op.drop_table('benchmarks')
    op.drop_index(op.f('ix_assets_ip_address'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_hostname'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
