"""add_asset_fields_and_pagination

Revision ID: 3f0df7136dc7
Revises: 254c73c7a415
Create Date: 2026-04-27 04:02:54.810190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f0df7136dc7'
down_revision: Union[str, Sequence[str], None] = '254c73c7a415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('os_family', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('os_version', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('assets', sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'last_seen_at')
    op.drop_column('assets', 'is_active')
    op.drop_column('assets', 'os_version')
    op.drop_column('assets', 'os_family')
    # ### end Alembic commands ###
