"""add_auto_scan_and_sync_fields

Revision ID: 664816ef8197
Revises: 3f0df7136dc7
Create Date: 2026-04-27 04:19:38.746902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664816ef8197'
down_revision: Union[str, Sequence[str], None] = '3f0df7136dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('auto_scan', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'auto_scan')
    # ### end Alembic commands ###
