"""Add score to AuditInfo

Revision ID: c87659399e12
Revises: d804998b6c3f
Create Date: 2026-04-27 14:19:17.919770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87659399e12'
down_revision: Union[str, Sequence[str], None] = 'd804998b6c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_infos', sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_infos', 'score')
    # ### end Alembic commands ###
