"""Add state and task_id to AuditInfo

Revision ID: d804998b6c3f
Revises: 664816ef8197
Create Date: 2026-04-27 14:07:28.565578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd804998b6c3f'
down_revision: Union[str, Sequence[str], None] = '664816ef8197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_infos', sa.Column('task_id', sa.String(length=255), nullable=True))
    op.add_column('audit_infos', sa.Column('state', sa.String(length=50), nullable=True))
    op.execute("UPDATE audit_infos SET state = 'PENDING'")
    op.alter_column('audit_infos', 'state', nullable=False)
    op.drop_index('ix_audit_infos_audit_id', table_name='audit_infos')
    op.create_index(op.f('ix_audit_infos_task_id'), 'audit_infos', ['task_id'], unique=True)
    op.drop_column('audit_infos', 'audit_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_infos', sa.Column('audit_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audit_infos_task_id'), table_name='audit_infos')
    op.create_index('ix_audit_infos_audit_id', 'audit_infos', ['audit_id'], unique=True)
    op.drop_column('audit_infos', 'state')
    op.drop_column('audit_infos', 'task_id')
    # ### end Alembic commands ###
